"""Controlled vocabularies for ASTRA.

Every enumeration here is part of the API contract: it is exported through the
OpenAPI schema and regenerated into TypeScript in ``packages/contracts`` so the
frontend can never invent a value the backend does not know about.
"""

from __future__ import annotations

from enum import StrEnum


class ProvenanceClass(StrEnum):
    """Provenance classes per CLAUDE.md §4.2 — enforced in code, surfaced in UI.

    Every layer, table and field carries exactly one of these.
    """

    REAL_OPEN = "REAL_OPEN"
    """Real public dataset, unmodified."""

    DERIVED = "DERIVED"
    """Computed by ASTRA from REAL_OPEN inputs (slope from DEM, HAND, kernel density)."""

    SYNTHETIC_CALIBRATED = "SYNTHETIC_CALIBRATED"
    """Generated by ASTRA, statistically calibrated to the real study area, fictional."""

    DEMO_CONFIG = "DEMO_CONFIG"
    """An ASTRA-chosen threshold, weight or policy constant. Not a government rule."""


class HazardType(StrEnum):
    """The four modelled hazards (CLAUDE.md §5.1)."""

    LANDSLIDE = "LANDSLIDE"
    FLOOD = "FLOOD"
    CLOUDBURST = "CLOUDBURST"
    COASTAL_EROSION = "COASTAL_EROSION"


class ZoneClass(StrEnum):
    """Red-zone severity classes derived from the composite susceptibility surface.

    These are ASTRA analytical classifications, never statutory designations.
    """

    CRITICAL = "CRITICAL"
    ELEVATED = "ELEVATED"
    WATCH = "WATCH"
    LOW = "LOW"


class PhaseTier(StrEnum):
    """Relocation phasing tiers — the PS's exact three-tier language (§5.3)."""

    IMMEDIATE = "IMMEDIATE"
    SHORT_TERM = "SHORT_TERM"
    MEDIUM_TERM = "MEDIUM_TERM"
    NOT_PRIORITISED = "NOT_PRIORITISED"
    CAPACITY_BLOCKED = "CAPACITY_BLOCKED"
    """High risk but no feasible matched capacity — actionable intelligence, not a rank."""


class ServiceType(StrEnum):
    """Services whose per-service capacity is computed in Engine 4 (§5.4 step 3)."""

    LAND = "LAND"
    SHELTER = "SHELTER"
    WATER = "WATER"
    SANITATION = "SANITATION"
    HEALTHCARE = "HEALTHCARE"
    POWER = "POWER"
    ACCESS = "ACCESS"


class SuitabilityGate(StrEnum):
    """Hard binary gates a candidate site must pass (§5.4 step 1).

    A gate failure is reported as a named gate, never folded into a low score.
    """

    OUTSIDE_HAZARD_ZONES = "OUTSIDE_HAZARD_ZONES"
    SLOPE_BUILDABLE = "SLOPE_BUILDABLE"
    LANDCOVER_PERMITTED = "LANDCOVER_PERMITTED"
    ABOVE_FLOOD_LEVEL = "ABOVE_FLOOD_LEVEL"
    ROAD_ACCESSIBLE = "ROAD_ACCESSIBLE"


class RouteProfile(StrEnum):
    """Routing objectives returned per origin/destination pair (§5.5)."""

    FASTEST = "FASTEST"
    SAFEST = "SAFEST"


class PerturbationKind(StrEnum):
    """What a scenario changes about the world (§5.7).

    Each kind enters the pipeline at exactly one stage, and the stage decides how
    far the change propagates. A rainfall multiplier re-scores hazard and
    therefore everything downstream of it; a site capacity loss changes nothing
    about the hazard surface and only re-plans. Keeping that explicit is what
    makes a scenario diff readable rather than a wall of changed numbers.
    """

    #: Multiplies rainfall intensity and extreme-rain days. Enters at Engine 1.
    RAINFALL_MULTIPLIER = "RAINFALL_MULTIPLIER"
    #: Adds to the normalised landslide susceptibility. Enters at Engine 1.
    LANDSLIDE_SHIFT = "LANDSLIDE_SHIFT"
    #: Closes one road segment. Enters at Engine 5.
    ROAD_CLOSURE = "ROAD_CLOSURE"
    #: Removes a share of one site's service supply. Enters at Engine 4.
    SITE_CAPACITY_LOSS = "SITE_CAPACITY_LOSS"
    #: Adds supply of one service at one site. Enters at Engine 4.
    SERVICE_UPGRADE = "SERVICE_UPGRADE"
    #: Takes a candidate site out of consideration entirely. Enters at Engine 4.
    SITE_DISABLED = "SITE_DISABLED"
    #: Multiplies one habitation's population, or all of them. Enters at Engine 2.
    POPULATION_MULTIPLIER = "POPULATION_MULTIPLIER"



class ConfidenceBand(StrEnum):
    """Evidence confidence — orthogonal to priority, never multiplied into it (§5.2)."""

    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class SolverStatus(StrEnum):
    """Outcome of the relocation optimiser (§5.6)."""

    OPTIMAL = "OPTIMAL"
    FEASIBLE = "FEASIBLE"
    INFEASIBLE = "INFEASIBLE"
    FALLBACK = "FALLBACK"
    """Deterministic greedy fallback ran because the solver hit its time limit."""


class RunStage(StrEnum):
    """Pipeline stages emitted over SSE and rendered by the execution graph (§9)."""

    INGEST = "INGEST"
    HAZARD = "HAZARD"
    EXPOSURE_VULNERABILITY = "EXPOSURE_VULNERABILITY"
    SITE_CAPACITY = "SITE_CAPACITY"
    ROUTE_RELIABILITY = "ROUTE_RELIABILITY"
    OPTIMISATION = "OPTIMISATION"
    DECISION_BRIEF = "DECISION_BRIEF"


class RunStageStatus(StrEnum):
    """Lifecycle of a single pipeline stage. Drives node state in the graph."""

    PENDING = "PENDING"
    STARTED = "STARTED"
    PROGRESS = "PROGRESS"
    COMPLETED = "COMPLETED"
    WARNING = "WARNING"
    FAILED = "FAILED"


class RunStatus(StrEnum):
    """Where one pipeline execution has got to (§9).

    A run is a real thing that starts, takes time and can fail. The interface
    reads this rather than assuming a run that was requested has succeeded.
    """

    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class EventType(StrEnum):
    """Real-time ingest event kinds accepted by POST /events (§5.8).

    Each kind enters the pipeline at exactly one surface, the same discipline a
    scenario perturbation follows. The difference is that an event is an
    *observation with a place and a time* rather than a hypothesis, so it also
    carries a footprint: the ground the observation actually speaks for, and the
    only ground that is re-scored because of it.
    """

    #: Measured rainfall over a gauge or radar cell. Raises rainfall intensity
    #: and the extreme-rain-day count inside its footprint.
    RAINFALL_OBSERVATION = "RAINFALL_OBSERVATION"
    #: A slope failure, washout or inundation that has already happened. Adds
    #: severity-weighted density to the incident surface.
    INCIDENT_REPORT = "INCIDENT_REPORT"
    #: A field officer's observation of ground instability - tension cracks,
    #: seepage, movement. Adds to the terrain instability *input*, never to the
    #: finished score, so the factor decomposition stays an honest account.
    FIELD_EVIDENCE = "FIELD_EVIDENCE"
    #: A road reported impassable. Enters at the route engine rather than the
    #: hazard surface: a blocked road changes who can get where, not how steep
    #: the hillside above it is.
    INFRASTRUCTURE_STATUS = "INFRASTRUCTURE_STATUS"


class DecisionState(StrEnum):
    """Human-in-the-loop state of a computed plan (§6). ASTRA never decides."""

    COMPUTED = "COMPUTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    OVERRIDDEN = "OVERRIDDEN"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"
    """A newly ingested event invalidated part of an approved plan."""


class StructureType(StrEnum):
    """Structural typology proxy used in the vulnerability composite (§5.2)."""

    KUTCHA = "KUTCHA"
    SEMI_PUCCA = "SEMI_PUCCA"
    PUCCA = "PUCCA"


class RoadClass(StrEnum):
    """OSM-derived road classes used for free-flow speed and reliability (§5.5)."""

    NATIONAL_HIGHWAY = "NATIONAL_HIGHWAY"
    STATE_HIGHWAY = "STATE_HIGHWAY"
    DISTRICT_ROAD = "DISTRICT_ROAD"
    VILLAGE_ROAD = "VILLAGE_ROAD"
    TRACK = "TRACK"
